name: Deploy Dev Infra

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'infrastructure/**'
      - '.github/workflows/deploy-dev-infra.yml'
      - '.github/workflows/deploy-infra.yml'

concurrency:
  group: deploy-dev-infra
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy-infra:
    name: Deploy Infra to Dev
    uses: ./.github/workflows/deploy-infra.yml
    with:
      environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DEPLOY_AWS_REGION: ${{ secrets.DEPLOY_AWS_REGION }}
      AMPLIFY_GITHUB_TOKEN: ${{ secrets.AMPLIFY_GITHUB_TOKEN }}
